### ISSUE TITLE
Error when running

### ISSUE THREAD

**Issue by dk865** [AhmedDawoud3/Love2d-Midi-Visualizer#1]
Error

main.lua:5: module 'luamidi' not found:
no field package.preload['luamidi']
no 'luamidi' in LOVE game directories.
no file 'luamidi' in LOVE paths.
no file './luamidi.lua'
no file '/usr/share/luajit-2.1.0-beta3/luamidi.lua'
no file '/usr/local/share/lua/5.1/luamidi.lua'
no file '/usr/local/share/lua/5.1/luamidi/init.lua'
no file '/usr/share/lua/5.1/luamidi.lua'
no file '/usr/share/lua/5.1/luamidi/init.lua'
no file './luamidi.so'
no file '/usr/local/lib/lua/5.1/luamidi.so'
no file '/usr/lib/x86_64-linux-gnu/lua/5.1/luamidi.so'
no file '/usr/local/lib/lua/5.1/loadall.so'

Traceback

[C]: in function 'require'
main.lua:5: in main chunk
[C]: in function 'require'
[C]: in function 'xpcall'
[C]: in function 'xpcall'

**Comment by AhmedDawoud3** [comment]
Make sure to download the luamidi.dll file
Follow the [Getting Started](https://github.com/AhmedDawoud3/Love2d-Midi-Visualizer#getting-started) section
